new_topic_button_icon:
  default: "far-pen-to-square"
new_topic_button_text:
  default: ""
new_topic_button_title:
  default: "Create New Topics"
hide_default_button:
  default: false
show_to_anon:
  default: false
